### ISSUE TITLE
bind-reload not working

### ISSUE THREAD

**Issue by jashanpreetsingh** [Zizzamia/ng-tasty#114]
I have a case where I want to reload my table on a button click. But when I am adding bind-reload attribute it show no response and no call is made to API. FYI I am implementing Service Side Table.
HTML:
![html](https://cloud.githubusercontent.com/assets/11288943/6618104/dc1ce4ce-c8e5-11e4-8433-6e58cf93f8fb.JPG)

Javascript:
![javascript](https://cloud.githubusercontent.com/assets/11288943/6618123/12e34cb4-c8e6-11e4-944d-5936a50c826e.JPG)

If I remove bind-reload attribute then it works fine, table is loading but then I can't reload/refresh it. 

Much appreciated.

**Comment by Zizzamia** [comment]
After few investigation I discover the table reload only if you change the filter value, here the exactly line of code does that https://github.com/Zizzamia/ng-tasty/blob/839f9fc4f13a6dd33881a83d9dda0bd32ca1a182/src/component/table.js#L351

This is a bug, because the correct behavior instead should be the possibility to control the reload of resource inside the table in every case.

ThankYou @jashanpreetsingh to post this issue.

**Comment by vidvid** [comment]
@Zizzamia can you tell me how to see this working in the current version?

**Comment by shyamprasathbrigita** [comment]
I am also trying to reload the table using bind-reload without using filter option. But callback is not triggered. I think still there is a bug. I keep nothing in filter object. 

$scope.filterBy = {};

**Comment by Zizzamia** [comment]
Here is the working example http://zizzamia.com/ng-tasty/directive/table-server-side/reload,
@shyamprasathbrigita can you please show me an example of the code you are trying to run please.

**Comment by shyamprasathbrigita** [comment]
hi Zizzamia , thank you for your response. Here is my code

JS code:

     // Init the datatable for product
    
        $scope.init = {
          'count': 5,
          'page': 1,
          'sortBy': 'name',
          'sortOrder': 'dsc'
        };
        
        $scope.reloadCallback = function () {};

        $scope.filterBy = {};

        $scope.search = function () {
            
                $scope.reloadCallback();
        };

        $scope.getSalesPOItems = function (params, paramsObj) {

              return SalesService.getSalesPOListDatatable(paramsObj).then(function(data){

                      return {
                              'rows': data.rows,
                              'header': [],
                              'pagination': data.pagination,
                              'sortBy': '',
                              'sortOrder': ''
                      };
              });

        };

Markup:

<div class="form-group">
  <div class="col-sm-3">
    <button class="btn btn-primary" ng-click="search()">Search</button>
  </div>
</div>
            <div tasty-table bind-resource-callback="getSalesPOItems" bind-init="init" bind-filters="filterBy" rows="rows">
                <table class="table table-striped table-condensed table-responsive table-hover">
                  <thead>
                    <tr>
                        <th>S.No</th>
                        <th>PO Number</th>
                        <th>Date</th>
                        <th>Expected Delivery Date</th>
                        <th>Expiry Date</th>
                        <th>Full Profile</th>
                    </tr>
                  <thead>
                  <tbody>
                    <tr ng-repeat="r in rows">
                        <td>{{ $index+1 }}</td>
                        <td>{{ r.po_number }}</td>
                        <td>{{ r.date }}</td>
                        <td>{{ r.expected_delivery_date }}</td>
                        <td>{{ r.expiry_date }}</td>
                        <td><a ui-sref="sales.viewpo({POId: r.id})">view</td>
                    </tr>
                  </tbody>
                </table>
                <div tasty-pagination></div>
            </div>

Yes, I am following the same example which you given. In that, search reload callback is triggered when clicking the search button without making any changes in the filter. But the above code does not perform as expected. Since I have much work load I am not able to dip into the plugin source code. Please reply your comments as soon as possible.

**Comment by amirafroozeh1** [comment]
I have the same problem. When I want to delete a row and I call manually reloadCallBack, it does not refresh the table.

**Comment by Zizzamia** [comment]
I guys, can you make a new issue about this. I will take a look of that. :)

**Comment by dangergeowolf** [comment]
Hi, has there been any resolution to this?  I'm also having problems in getting a reload callback when changing the filter value.
